import React from "react";
import AccordionItem from "./AccordionItem";
import "./App.css";

/**
 * ファイル構造データの定義
 * file_tree.txt に基づいて生成
 */
const FILE_STRUCTURE = [
  {
    id: "public_html",
    name: "public_html", // public_html_tree.txt の '.'
    children: [
      {
        id: "app-admin",
        name: "app-admin.kizuki.or.jp",
        children: [], // 第2階層
      },
      {
        id: "app-super",
        name: "app-super.kizuki.or.jp",
        children: [], // 第2階層
      },
      {
        id: "app",
        name: "app.kizuki.or.jp",
        children: [], // 第2階層
      },
      { id: "apple-touch-icon", name: "apple-touch-icon.png" },
      {
        id: "asset",
        name: "asset",
        children: [], // 第2階層
      },
      {
        id: "assets",
        name: "assets",
        children: [], // 第2階層
      },
      {
        id: "csv",
        name: "csv",
        children: [], // 第2階層
      },
      { id: "favicon", name: "favicon.ico" },
      // file_tree.txt 自体は除外
      {
        id: "form2",
        name: "form2",
        children: [], // 第2階層
      },
      { id: "google-1", name: "google621bb49a4aa7bea4.html" },
      { id: "google-2", name: "google7c02369e2e4cc9ce.html" },
      { id: "google-3", name: "googlea5d71dd0983225a5.html" },
      { id: "google-4", name: "googlee5b8493aee483d20.html" },
      { id: "index-php", name: "index.php" },
      {
        id: "ir",
        name: "ir",
        children: [], // 第2階層
      },
      {
        id: "kbc-test2023",
        name: "kbc-test2023.kizuki.or.jp",
        children: [], // 第2階層
      },
      {
        id: "kbc",
        name: "kbc.kizuki.or.jp",
        children: [], // 第2階層
      },
      { id: "kizuki-csv", name: "kizuki_sf7dbplugin_submits.csv" },
      {
        id: "onlinelp",
        name: "onlinelp",
        children: [], // 第2階層
      },
      {
        id: "ouen-assets",
        name: "ouen-assets",
        children: [], // 第2階層
      },
      { id: "privacy", name: "privacy.html" },
      { id: "robots", name: "robots.txt" },
      { id: "setcookie", name: "setcookie.php" },
      {
        id: "stg",
        name: "stg.kizuki.or.jp",
        children: [], // 第2階層
      },
      {
        id: "test",
        name: "test.kizuki.or.jp",
        children: [], // 第2階層
      },
      {
        id: "test2023",
        name: "test2023.kizuki.or.jp",
        children: [], // 第2階層
      },
      {
        id: "transition-12768",
        name: "transition-12768",
        children: [], // 第2階層
      },
      {
        id: "transition-13220",
        name: "transition-13220",
        children: [], // 第2階層
      },
      {
        id: "transition-15556",
        name: "transition-15556",
        children: [], // 第2階層
      },
      {
        id: "transition-15629",
        name: "transition-15629",
        children: [], // 第2階層
      },
      {
        id: "transition-23680",
        name: "transition-23680",
        children: [], // 第2階層
      },
      {
        id: "transition-25761",
        name: "transition-25761",
        children: [], // 第2階層
      },
      {
        id: "transition-26135",
        name: "transition-26135",
        children: [], // 第2階層
      },
      {
        id: "transition-26268",
        name: "transition-26268",
        children: [], // 第2階層
      },
      {
        id: "transition-26285",
        name: "transition-26285",
        children: [], // 第2階層
      },
      {
        id: "transition-26545",
        name: "transition-26545",
        children: [], // 第2階層
      },
      {
        id: "wordpress",
        name: "wordpress",
        children: [
          // ▼ wordpress_tree.txt の内容 ▼
          { id: "wp-index-php", name: "index.php" },
          { id: "wp-license", name: "license.txt" },
          { id: "wp-loginUh9dNfDj", name: "loginUh9dNfDj.php" },
          { id: "wp-readme-ja", name: "readme-ja.html" },
          { id: "wp-readme", name: "readme.html" },
          { id: "wp-activate", name: "wp-activate.php" },
          { id: "wp-admin", name: "wp-admin", children: [] }, // フォルダ
          { id: "wp-blog-header", name: "wp-blog-header.php" },
          { id: "wp-comments-post", name: "wp-comments-post.php" },
          { id: "wp-config-sample", name: "wp-config-sample.php" },
          { id: "wp-config", name: "wp-config.php" },
          {
            id: "wp-content",
            name: "wp-content",
            children: [
              // ▼ wp-content_tree.txt (Source 6) の内容を反映 ▼
              {
                id: "wp-content-ai1wm-backups",
                name: "ai1wm-backups",
                children: [],
              },
              { id: "wp-content-index", name: "index.php" },
              { id: "wp-content-languages", name: "languages", children: [] },
              { id: "wp-content-plugins", name: "plugins", children: [] },
              {
                id: "wp-content-themes", // IDを調整
                name: "themes",
                children: [
                  // ▼ themes_tree.txt の内容 ▼
                  { id: "themes-index-php", name: "index.php" },
                  {
                    id: "themes-kizuki-or-jp",
                    name: "kizuki_or_jp",
                    children: [
                      // ▼ kizuki_or_jp_tree.txt の内容 ▼
                      { id: "kizuki-404-company", name: "404-company.php" },
                      { id: "kizuki-404", name: "404.php" },
                      {
                        id: "kizuki-aboutus",
                        name: "aboutus",
                        children: [
                          { id: "kizuki-aboutus-page-aboutus-4sou-facility", name: "page-aboutus-4sou-facility.php" },
                          { id: "kizuki-aboutus-page-aboutus-4sou-map", name: "page-aboutus-4sou-map.php" },
                          { id: "kizuki-aboutus-page-aboutus-4sou", name: "page-aboutus-4sou.php" },
                          { id: "kizuki-aboutus-page-aboutus-online-temp", name: "page-aboutus-online-temp.php" },
                          { id: "kizuki-aboutus-page-aboutus", name: "page-aboutus.php" },
                          { id: "kizuki-aboutus-page-aboutusTop", name: "page-aboutusTop.php" },
                          { id: "kizuki-aboutus-sidebar-aboutus", name: "sidebar-aboutus.php" },
                        ],
                      },
                      { id: "kizuki-archive-blog", name: "archive-blog.php" },
                      {
                        id: "kizuki-archive-company-1904",
                        name: "archive-company-1904.php",
                      },
                      {
                        id: "kizuki-archive-company",
                        name: "archive-company.php",
                      },
                      {
                        id: "kizuki-archive-kbc-test",
                        name: "archive-kbc-test.php",
                      },
                      { id: "kizuki-archive-kbc", name: "archive-kbc.php" },
                      {
                        id: "kizuki-archive-teachers",
                        name: "archive-teachers.php",
                      },
                      {
                        id: "kizuki-archive-voice-test",
                        name: "archive-voice-test.php",
                      },
                      { id: "kizuki-archive-voice", name: "archive-voice.php" },
                      { id: "kizuki-archive", name: "archive.php" },
                      {
                        id: "kizuki-backup-archive-teachers",
                        name: "backup-before202001_archive-teachers.php",
                      },
                      {
                        id: "kizuki-blog",
                        name: "blog",
                        children: [
                          { id: "kizuki-blog-sidebar-new-blog", name: "sidebar-new-blog.php" },
                          { id: "kizuki-blog-sidebar-recommend-blog", name: "sidebar-recommend-blog.php" },
                          { id: "kizuki-blog-sidebar-related-blog", name: "sidebar-related-blog.php" },
                        ],
                      },
                      { id: "kizuki-category-news", name: "category-news.php" },
                      { id: "kizuki-category", name: "category.php" },
                      {
                        id: "kizuki-company",
                        name: "company",
                        children: [
                          { id: "kizuki-company-foot-company", name: "foot-company.php" },
                          { id: "kizuki-company-footer-company", name: "footer-company.php" },
                          { id: "kizuki-company-gnavi-company", name: "gnavi-company.php" },
                          { id: "kizuki-company-head-company-1904", name: "head-company-1904.php" },
                          { id: "kizuki-company-head-company-lp", name: "head-company-lp.php" },
                          { id: "kizuki-company-head-company", name: "head-company.php" },
                          { id: "kizuki-company-header-company", name: "header-company.php" },
                          {
                            id: "kizuki-company-lp-parts",
                            name: "lp-parts",
                            children: [
                              { id: "kizuki-company-lp-parts-lp-cta-footer-teacher", name: "lp_cta_footer_teacher.php" },
                              { id: "kizuki-company-lp-parts-lp-cta-teacher", name: "lp_cta_teacher.php" },
                              { id: "kizuki-company-lp-parts-lp-header-teacher", name: "lp_header_teacher.php" },
                              { id: "kizuki-company-lp-parts-lp-teacher-css", name: "lp_teacher.css" },
                            ],
                          },
                          { id: "kizuki-company-page-company-lp", name: "page-company-lp.php" },
                          { id: "kizuki-company-sidebar-company", name: "sidebar-company.php" },
                        ],
                      },
                      {
                        id: "kizuki-contact",
                        name: "contact",
                        children: [
                          { id: "kizuki-contact-page-contact", name: "page-contact.php" },
                          { id: "kizuki-contact-sidebar-contact", name: "sidebar-contact.php" },
                        ],
                      },
                      {
                        id: "kizuki-courses",
                        name: "courses",
                        children: [
                          { id: "kizuki-courses-page-course", name: "page-course.php" },
                          { id: "kizuki-courses-page-courses", name: "page-courses.php" },
                          { id: "kizuki-courses-sidebar-courses", name: "sidebar-courses.php" },
                        ],
                      },
                      { id: "kizuki-date", name: "date.php" },
                      {
                        id: "kizuki-donation",
                        name: "donation",
                        children: [
                          { id: "kizuki-donation-page-donation", name: "page-donation.php" },
                          { id: "kizuki-donation-sidebar-donation", name: "sidebar-donation.php" },
                        ],
                      },
                      { id: "kizuki-foot-top", name: "foot-top.php" },
                      { id: "kizuki-foot", name: "foot.php" },
                      { id: "kizuki-footer", name: "footer.php" },
                      {
                        id: "kizuki-front-page-test",
                        name: "front-page-test.php",
                      },
                      { id: "kizuki-front-page", name: "front-page.php" },
                      { id: "kizuki-functions", name: "functions.php" },
                      {
                        id: "kizuki-futoko-lp",
                        name: "futoko_lp",
                        children: [
                          { id: "kizuki-futoko-lp-campaign-popup", name: "lp_campaign_popup.php" },
                          { id: "kizuki-futoko-lp-css-cta-4", name: "lp_css_cta-4.php" },
                          { id: "kizuki-futoko-lp-css-ctas", name: "lp_css_ctas.php" },
                          { id: "kizuki-futoko-lp-cta-banner", name: "lp_cta_banner.php" },
                          { id: "kizuki-futoko-lp-cta-CL", name: "lp_cta_CL.php" },
                          { id: "kizuki-futoko-lp-cta-footer-CL", name: "lp_cta_footer_CL.php" },
                          { id: "kizuki-futoko-lp-cta-footer-media-tel", name: "lp_cta_footer_media_tel.php" },
                          { id: "kizuki-futoko-lp-cta-footer-notel", name: "lp_cta_footer_notel.php" },
                          { id: "kizuki-futoko-lp-cta-footer-teacher", name: "lp_cta_footer_teacher.php" },
                          { id: "kizuki-futoko-lp-cta-footer-tel", name: "lp_cta_footer_tel.php" },
                          { id: "kizuki-futoko-lp-cta-footer-tel2", name: "lp_cta_footer_tel2.php" },
                          { id: "kizuki-futoko-lp-cta-footer-tel3", name: "lp_cta_footer_tel3.php" },
                          { id: "kizuki-futoko-lp-cta-footer-yagaku-notel", name: "lp_cta_footer_yagaku_notel.php" },
                          { id: "kizuki-futoko-lp-cta-footer-yagaku-tel3", name: "lp_cta_footer_yagaku_tel3.php" },
                          { id: "kizuki-futoko-lp-cta-footer", name: "lp_cta_footer.php" },
                          { id: "kizuki-futoko-lp-cta-form-pamphlet", name: "lp_cta_form_pamphlet.php" },
                          { id: "kizuki-futoko-lp-cta-media-tel", name: "lp_cta_media_tel.php" },
                          { id: "kizuki-futoko-lp-cta-notel", name: "lp_cta_notel.php" },
                          { id: "kizuki-futoko-lp-cta-teacher", name: "lp_cta_teacher.php" },
                          { id: "kizuki-futoko-lp-cta-tel", name: "lp_cta_tel.php" },
                          { id: "kizuki-futoko-lp-cta-tel2", name: "lp_cta_tel2.php" },
                          { id: "kizuki-futoko-lp-cta-tel3", name: "lp_cta_tel3.php" },
                          { id: "kizuki-futoko-lp-cta-yagaku-notel", name: "lp_cta_yagaku_notel.php" },
                          { id: "kizuki-futoko-lp-cta-yagaku-tel3", name: "lp_cta_yagaku_tel3.php" },
                          { id: "kizuki-futoko-lp-cta", name: "lp_cta.php" },
                          { id: "kizuki-futoko-lp-header-blank-tel", name: "lp_header_blank_tel.php" },
                          { id: "kizuki-futoko-lp-header-chutai-notel", name: "lp_header_chutai_notel.php" },
                          { id: "kizuki-futoko-lp-header-chutai-tel", name: "lp_header_chutai_tel.php" },
                          { id: "kizuki-futoko-lp-header-daigaku-tel", name: "lp_header_daigaku_tel.php" },
                          { id: "kizuki-futoko-lp-header-goal-tel3", name: "lp_header_goal_tel3.php" },
                          { id: "kizuki-futoko-lp-header-goal", name: "lp_header_goal.php" },
                          { id: "kizuki-futoko-lp-header-kyugaku-tel", name: "lp_header_kyugaku_tel.php" },
                          { id: "kizuki-futoko-lp-header-line", name: "lp_header_line.php" },
                          { id: "kizuki-futoko-lp-header-manabi-notel", name: "lp_header_manabi_notel.php" },
                          { id: "kizuki-futoko-lp-header-manabi-tel", name: "lp_header_manabi_tel.php" },
                          { id: "kizuki-futoko-lp-header-manto-tel3", name: "lp_header_manto_tel3.php" },
                          { id: "kizuki-futoko-lp-header-media-tel", name: "lp_header_media_tel.php" },
                          { id: "kizuki-futoko-lp-header-nolink", name: "lp_header_nolink.php" },
                          { id: "kizuki-futoko-lp-header-otona-a", name: "lp_header_otona_a.php" },
                          { id: "kizuki-futoko-lp-header-otona-e", name: "lp_header_otona_e.php" },
                          { id: "kizuki-futoko-lp-header-otona-m", name: "lp_header_otona_m.php" },
                          { id: "kizuki-futoko-lp-header-otona-s-uni", name: "lp_header_otona_s_uni.php" },
                          { id: "kizuki-futoko-lp-header-otona-s", name: "lp_header_otona_s.php" },
                          { id: "kizuki-futoko-lp-header-otona-tel", name: "lp_header_otona_tel.php" },
                          { id: "kizuki-futoko-lp-header-otona-tel2", name: "lp_header_otona_tel2.php" },
                          { id: "kizuki-futoko-lp-header-otona-tel3", name: "lp_header_otona_tel3.php" },
                          { id: "kizuki-futoko-lp-header-otona", name: "lp_header_otona.php" },
                          { id: "kizuki-futoko-lp-header-ronin-tel", name: "lp_header_ronin_tel.php" },
                          { id: "kizuki-futoko-lp-header-teacher", name: "lp_header_teacher.php" },
                          { id: "kizuki-futoko-lp-header-tel-chs", name: "lp_header_tel_chs.php" },
                          { id: "kizuki-futoko-lp-header-tel", name: "lp_header_tel.php" },
                          { id: "kizuki-futoko-lp-header-tel3", name: "lp_header_tel3.php" },
                          { id: "kizuki-futoko-lp-header-winter-tel3", name: "lp_header_winter_tel3.php" },
                          { id: "kizuki-futoko-lp-header-winter", name: "lp_header_winter.php" },
                          { id: "kizuki-futoko-lp-header-yagaku-notel", name: "lp_header_yagaku_notel.php" },
                          { id: "kizuki-futoko-lp-header-yagaku-tel3", name: "lp_header_yagaku_tel3.php" },
                          { id: "kizuki-futoko-lp-header-yorisoi-notel", name: "lp_header_yorisoi_notel.php" },
                          { id: "kizuki-futoko-lp-header-yorisoi-tel", name: "lp_header_yorisoi_tel.php" },
                          { id: "kizuki-futoko-lp-header-yorisoi-tel2", name: "lp_header_yorisoi_tel2.php" },
                          { id: "kizuki-futoko-lp-header-yorisoi-tel3", name: "lp_header_yorisoi_tel3.php" },
                          { id: "kizuki-futoko-lp-header-yorisoi", name: "lp_header_yorisoi.php" },
                          { id: "kizuki-futoko-lp-header", name: "lp_header.php" },
                          { id: "kizuki-futoko-lp-page-10179-transition", name: "page-10179-transition.php" },
                          { id: "kizuki-futoko-lp-page-10197-transition", name: "page-10197-transition.php" },
                          { id: "kizuki-futoko-lp-page-10524-transition", name: "page-10524-transition.php" },
                          { id: "kizuki-futoko-lp-page-10674-transition", name: "page-10674-transition.php" },
                          { id: "kizuki-futoko-lp-page-11071-transition", name: "page-11071-transition.php" },
                          { id: "kizuki-futoko-lp-page-12768-transition", name: "page-12768-transition.php" },
                          { id: "kizuki-futoko-lp-page-13220-transition", name: "page-13220-transition.php" },
                          { id: "kizuki-futoko-lp-page-15556-transition", name: "page-15556-transition.php" },
                          { id: "kizuki-futoko-lp-page-15629-transition", name: "page-15629-transition.php" },
                          { id: "kizuki-futoko-lp-page-16254-transition", name: "page-16254-transition.php" },
                          { id: "kizuki-futoko-lp-page-16814-transition", name: "page-16814-transition.php" },
                          { id: "kizuki-futoko-lp-page-18746-transition", name: "page-18746-transition.php" },
                          { id: "kizuki-futoko-lp-page-18806-transition", name: "page-18806-transition.php" },
                          { id: "kizuki-futoko-lp-page-18926-transition", name: "page-18926-transition.php" },
                          { id: "kizuki-futoko-lp-page-19036-transition", name: "page-19036-transition.php" },
                          { id: "kizuki-futoko-lp-page-19830-transition", name: "page-19830-transition.php" },
                          { id: "kizuki-futoko-lp-page-20554-transition", name: "page-20554-transition.php" },
                          { id: "kizuki-futoko-lp-page-20604-transition", name: "page-20604-transition.php" },
                          { id: "kizuki-futoko-lp-page-20610-transition", name: "page-20610-transition.php" },
                          { id: "kizuki-futoko-lp-page-20687-transition", name: "page-20687-transition.php" },
                          { id: "kizuki-futoko-lp-page-20723-transition", name: "page-20723-transition.php" },
                          { id: "kizuki-futoko-lp-page-20898-transition", name: "page-20898-transition.php" },
                          { id: "kizuki-futoko-lp-page-21102-transition", name: "page-21102-transition.php" },
                          { id: "kizuki-futoko-lp-page-21128-transition", name: "page-21128-transition.php" },
                          { id: "kizuki-futoko-lp-page-21152-transition", name: "page-21152-transition.php" },
                          { id: "kizuki-futoko-lp-page-21190-transition", name: "page-21190-transition.php" },
                          { id: "kizuki-futoko-lp-page-21351-transition", name: "page-21351-transition.php" },
                          { id: "kizuki-futoko-lp-page-21544-transition", name: "page-21544-transition.php" },
                          { id: "kizuki-futoko-lp-page-22308-transition", name: "page-22308-transition.php" },
                          { id: "kizuki-futoko-lp-page-22364-transition", name: "page-22364-transition.php" },
                          { id: "kizuki-futoko-lp-page-22684-transition", name: "page-22684-transition.php" },
                          { id: "kizuki-futoko-lp-page-22871-transition", name: "page-22871-transition.php" },
                          { id: "kizuki-futoko-lp-page-23424-transition", name: "page-23424-transition.php" },
                          { id: "kizuki-futoko-lp-page-23680-transition", name: "page-23680-transition.php" },
                          { id: "kizuki-futoko-lp-page-25761-transition", name: "page-25761-transition.php" },
                          { id: "kizuki-futoko-lp-page-26135-transition", name: "page-26135-transition.php" },
                          { id: "kizuki-futoko-lp-page-26268-transition", name: "page-26268-transition.php" },
                          { id: "kizuki-futoko-lp-page-26285-transition", name: "page-26285-transition.php" },
                          { id: "kizuki-futoko-lp-page-26545-transition", name: "page-26545-transition.php" },
                          { id: "kizuki-futoko-lp-page-2731-transition", name: "page-2731-transition.php" },
                          { id: "kizuki-futoko-lp-page-27842-transition", name: "page-27842-transition.php" },
                          { id: "kizuki-futoko-lp-page-27949-transition", name: "page-27949-transition.php" },
                          { id: "kizuki-futoko-lp-page-28591-transition", name: "page-28591-transition.php" },
                          { id: "kizuki-futoko-lp-page-29028-transition", name: "page-29028-transition.php" },
                          { id: "kizuki-futoko-lp-page-29551-transition", name: "page-29551-transition.php" },
                          { id: "kizuki-futoko-lp-page-29908-transition", name: "page-29908-transition.php" },
                          { id: "kizuki-futoko-lp-page-30445-transition", name: "page-30445-transition.php" },
                          { id: "kizuki-futoko-lp-page-30615-transition", name: "page-30615-transition.php" },
                          { id: "kizuki-futoko-lp-page-30856-transition", name: "page-30856-transition.php" },
                          { id: "kizuki-futoko-lp-page-30903-transition", name: "page-30903-transition.php" },
                          { id: "kizuki-futoko-lp-page-31243-transition", name: "page-31243-transition.php" },
                          { id: "kizuki-futoko-lp-page-31755-transition", name: "page-31755-transition.php" },
                          { id: "kizuki-futoko-lp-page-32441-transition", name: "page-32441-transition.php" },
                          { id: "kizuki-futoko-lp-page-33021-transition", name: "page-33021-transition.php" },
                          { id: "kizuki-futoko-lp-page-33702-transition", name: "page-33702-transition.php" },
                          { id: "kizuki-futoko-lp-page-33793-transition", name: "page-33793-transition.php" },
                          { id: "kizuki-futoko-lp-page-34074-transition", name: "page-34074-transition.php" },
                          { id: "kizuki-futoko-lp-page-34317-transition", name: "page-34317-transition.php" },
                          { id: "kizuki-futoko-lp-page-34329-transition", name: "page-34329-transition.php" },
                          { id: "kizuki-futoko-lp-page-34407-transition", name: "page-34407-transition.php" },
                          { id: "kizuki-futoko-lp-page-34446-transition", name: "page-34446-transition.php" },
                          { id: "kizuki-futoko-lp-page-34577-transition", name: "page-34577-transition.php" },
                          { id: "kizuki-futoko-lp-page-34706-transition", name: "page-34706-transition.php" },
                          { id: "kizuki-futoko-lp-page-34726-transition", name: "page-34726-transition.php" },
                          { id: "kizuki-futoko-lp-page-34740-transition", name: "page-34740-transition.php" },
                          { id: "kizuki-futoko-lp-page-34823-transition", name: "page-34823-transition.php" },
                          { id: "kizuki-futoko-lp-page-34920-transition", name: "page-34920-transition.php" },
                          { id: "kizuki-futoko-lp-page-34946-transition", name: "page-34946-transition.php" },
                          { id: "kizuki-futoko-lp-page-35079-transition", name: "page-35079-transition.php" },
                          { id: "kizuki-futoko-lp-page-35326-transition", name: "page-35326-transition.php" },
                          { id: "kizuki-futoko-lp-page-35537-transition", name: "page-35537-transition.php" },
                          { id: "kizuki-futoko-lp-page-36116-transition", name: "page-36116-transition.php" },
                          { id: "kizuki-futoko-lp-page-36216-transition", name: "page-36216-transition.php" },
                          { id: "kizuki-futoko-lp-page-39322-transition", name: "page-39322-transition.php" },
                          { id: "kizuki-futoko-lp-page-39330-transition", name: "page-39330-transition.php" },
                          { id: "kizuki-futoko-lp-page-39365-transition", name: "page-39365-transition.php" },
                          { id: "kizuki-futoko-lp-page-49277-transition", name: "page-49277-transition.php" },
                          { id: "kizuki-futoko-lp-page-49946-transition", name: "page-49946-transition.php" },
                          { id: "kizuki-futoko-lp-page-50236-transition", name: "page-50236-transition.php" },
                          { id: "kizuki-futoko-lp-page-57907-transition", name: "page-57907-transition.php" },
                          { id: "kizuki-futoko-lp-page-blank-lp", name: "page-blank-lp.php" },
                          { id: "kizuki-futoko-lp-page-chs-2025summer", name: "page-chs-2025summer.php" },
                          { id: "kizuki-futoko-lp-page-chutai-lp-fc", name: "page-chutai-lp-fc.php" },
                          { id: "kizuki-futoko-lp-page-chutai-lp", name: "page-chutai-lp.php" },
                          { id: "kizuki-futoko-lp-page-community-transition", name: "page-community-transition.php" },
                          { id: "kizuki-futoko-lp-page-corres", name: "page-corres.php" },
                          { id: "kizuki-futoko-lp-page-dd-2025summer", name: "page-dd-2025summer.php" },
                          { id: "kizuki-futoko-lp-page-dd-hs-lp", name: "page-dd-hs-lp.php" },
                          { id: "kizuki-futoko-lp-page-dd-jhs-lp", name: "page-dd-jhs-lp.php" },
                          { id: "kizuki-futoko-lp-page-dd-kyoto-lp", name: "page-dd-kyoto-lp.php" },
                          { id: "kizuki-futoko-lp-page-dd-lp-fc", name: "page-dd-lp-fc.php" },
                          { id: "kizuki-futoko-lp-page-dd-lp", name: "page-dd-lp.php" },
                          { id: "kizuki-futoko-lp-page-dd-lp02", name: "page-dd-lp02.php" },
                          { id: "kizuki-futoko-lp-page-dd-ps-lp", name: "page-dd-ps-lp.php" },
                          { id: "kizuki-futoko-lp-page-freeschool-lp", name: "page-freeschool-lp.php" },
                          { id: "kizuki-futoko-lp-page-futoko-japan-notel", name: "page-futoko-japan-notel.php" },
                          { id: "kizuki-futoko-lp-page-futoko-japan", name: "page-futoko-japan.php" },
                          { id: "kizuki-futoko-lp-page-futoko-jhs-2025summer", name: "page-futoko-jhs-2025summer.php" },
                          { id: "kizuki-futoko-lp-page-futoko-kyoto-lp-notel", name: "page-futoko-kyoto-lp-notel.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp-fc", name: "page-futoko-lp-fc.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp-feetest", name: "page-futoko-lp-feetest.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp-square", name: "page-futoko-lp-square.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp-test", name: "page-futoko-lp-test.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp", name: "page-futoko-lp.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp2", name: "page-futoko-lp2.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp3", name: "page-futoko-lp3.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp4", name: "page-futoko-lp4.php" },
                          { id: "kizuki-futoko-lp-page-futoko-lp5", name: "page-futoko-lp5.php" },
                          { id: "kizuki-futoko-lp-page-futoko-notel", name: "page-futoko-notel.php" },
                          { id: "kizuki-futoko-lp-page-futoko-osaka-lp-notel", name: "page-futoko-osaka-lp-notel.php" },
                          { id: "kizuki-futoko-lp-page-futoko-osaka-lp-test", name: "page-futoko-osaka-lp-test.php" },
                          { id: "kizuki-futoko-lp-page-futoko-osaka-lp", name: "page-futoko-osaka-lp.php" },
                          { id: "kizuki-futoko-lp-page-futoko-ps-2025summer", name: "page-futoko-ps-2025summer.php" },
                          { id: "kizuki-futoko-lp-page-futoko-transition", name: "page-futoko-transition.php" },
                          { id: "kizuki-futoko-lp-page-gbp-yoyogi", name: "page-gbp-yoyogi.php" },
                          { id: "kizuki-futoko-lp-page-hikikomori-lp-fc", name: "page-hikikomori-lp-fc.php" },
                          { id: "kizuki-futoko-lp-page-hikikomori-transition", name: "page-hikikomori-transition.php" },
                          { id: "kizuki-futoko-lp-page-life-transition", name: "page-life-transition.php" },
                          { id: "kizuki-futoko-lp-page-media-transition", name: "page-media-transition.php" },
                          { id: "kizuki-futoko-lp-page-oya-community", name: "page-oya-community.php" },
                          { id: "kizuki-futoko-lp-page-ps-lp", name: "page-ps-lp.php" },
                          { id: "kizuki-futoko-lp-page-ronin-lp", name: "page-ronin-lp.php" },
                          { id: "kizuki-futoko-lp-page-sr-lp", name: "page-sr-lp.php" },
                          { id: "kizuki-futoko-lp-page-study-support-lp", name: "page-study-support-lp.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-2025summer", name: "page-syakaijin-2025summer.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp", name: "page-syakaijin-lp.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp02", name: "page-syakaijin-lp02.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp03", name: "page-syakaijin-lp03.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp04", name: "page-syakaijin-lp04.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp05", name: "page-syakaijin-lp05.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp06-science-uni", name: "page-syakaijin-lp06_science_uni.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp06", name: "page-syakaijin-lp06.php" },
                          { id: "kizuki-futoko-lp-page-syakaijin-lp07-science", name: "page-syakaijin-lp07_science.php" },
                          { id: "kizuki-futoko-lp-page-teacher-kamagaya", name: "page-teacher-kamagaya.php" },
                          { id: "kizuki-futoko-lp-page-teacher", name: "page-teacher.php" },
                          { id: "kizuki-futoko-lp-page-terakoya-lp", name: "page-terakoya-lp.php" },
                          { id: "kizuki-futoko-lp-page-winter-lp-notel", name: "page-winter-lp-notel.php" },
                          { id: "kizuki-futoko-lp-page-winter-lp", name: "page-winter-lp.php" },
                          { id: "kizuki-futoko-lp-page-winter02-lp-notel", name: "page-winter02-lp-notel.php" },
                          { id: "kizuki-futoko-lp-page-winter02-lp", name: "page-winter02-lp.php" },
                          { id: "kizuki-futoko-lp-page-yagaku-lp", name: "page-yagaku-lp.php" },
                          { id: "kizuki-futoko-lp-page-yagaku-lp02", name: "page-yagaku-lp02.php" },
                          { id: "kizuki-futoko-lp-tel-popup", name: "tel-popup.php" },
                        ],
                      },
                      { id: "kizuki-head-column", name: "head-column.php" },
                      { id: "kizuki-head", name: "head.php" },
                      { id: "kizuki-header", name: "header.php" },
                      { id: "kizuki-index", name: "index.php" },
                      {
                        id: "kizuki-juku-floating-cta",
                        name: "juku-floating-cta.php",
                      },
                      { id: "kizuki-juku-foot", name: "juku-foot.php" },
                      {
                        id: "kizuki-kbc",
                        name: "kbc",
                        children: [
                          { id: "kizuki-kbc-kbc-lp-css-cta-4", name: "kbc_lp_css_cta-4.php" },
                          { id: "kizuki-kbc-kbc-lp-css-cta-5", name: "kbc_lp_css_cta-5.php" },
                          { id: "kizuki-kbc-kbc-lp-css-tel-popup", name: "kbc_lp_css_tel-popup.php" },
                          { id: "kizuki-kbc-kbc-lp-css-temp", name: "kbc_lp_css_temp.php" },
                          { id: "kizuki-kbc-kbc-lp-cta-footer-tel", name: "kbc_lp_cta_footer_tel.php" },
                          { id: "kizuki-kbc-kbc-lp-cta-footer", name: "kbc_lp_cta_footer.php" },
                          { id: "kizuki-kbc-kbc-lp-cta-tel", name: "kbc_lp_cta_tel.php" },
                          { id: "kizuki-kbc-kbc-lp-cta", name: "kbc_lp_cta.php" },
                          { id: "kizuki-kbc-kbc-lp-header-career", name: "kbc_lp_header_career.php" },
                          { id: "kizuki-kbc-kbc-lp-header", name: "kbc_lp_header.php" },
                          { id: "kizuki-kbc-kbc-archive-column", name: "kbc-archive-column.php" },
                          { id: "kizuki-kbc-kbc-archive-news", name: "kbc-archive-news.php" },
                          { id: "kizuki-kbc-kbc-archive-staff", name: "kbc-archive-staff.php" },
                          { id: "kizuki-kbc-kbc-archive-voice", name: "kbc-archive-voice.php" },
                          { id: "kizuki-kbc-kbc-archive", name: "kbc-archive.php" },
                          { id: "kizuki-kbc-kbc-foot", name: "kbc-foot.php" },
                          { id: "kizuki-kbc-kbc-footer-chic", name: "kbc-footer-chic.php" },
                          { id: "kizuki-kbc-kbc-footer", name: "kbc-footer.php" },
                          { id: "kizuki-kbc-kbc-head", name: "kbc-head.php" },
                          { id: "kizuki-kbc-kbc-header-chic", name: "kbc-header-chic.php" },
                          { id: "kizuki-kbc-kbc-header", name: "kbc-header.php" },
                          { id: "kizuki-kbc-kbc-lp-test", name: "kbc-lp_test.php" },
                          { id: "kizuki-kbc-kbc-lp-ad-job", name: "kbc-lp-ad-job.php" },
                          { id: "kizuki-kbc-kbc-lp-ad-notel", name: "kbc-lp-ad-notel.php" },
                          { id: "kizuki-kbc-kbc-lp-ad", name: "kbc-lp-ad.php" },
                          { id: "kizuki-kbc-kbc-lp-depression-job", name: "kbc-lp-depression-job.php" },
                          { id: "kizuki-kbc-kbc-lp-depression-notel", name: "kbc-lp-depression-notel.php" },
                          { id: "kizuki-kbc-kbc-lp-depression", name: "kbc-lp-depression.php" },
                          { id: "kizuki-kbc-kbc-lp-features-notel", name: "kbc-lp-features-notel.php" },
                          { id: "kizuki-kbc-kbc-lp-job", name: "kbc-lp-job.php" },
                          { id: "kizuki-kbc-kbc-lp-notel", name: "kbc-lp-notel.php" },
                          { id: "kizuki-kbc-kbc-lp-phototest", name: "kbc-lp-phototest.php" },
                          { id: "kizuki-kbc-kbc-lp", name: "kbc-lp.php" },
                          { id: "kizuki-kbc-kbc-page", name: "kbc-page.php" },
                          { id: "kizuki-kbc-kbc-service", name: "kbc-service.php" },
                          { id: "kizuki-kbc-page-28081-transition", name: "page-28081-transition.php" },
                          { id: "kizuki-kbc-page-28128-transition", name: "page-28128-transition.php" },
                          { id: "kizuki-kbc-page-28168-transition", name: "page-28168-transition.php" },
                          { id: "kizuki-kbc-page-28252-transition", name: "page-28252-transition.php" },
                          { id: "kizuki-kbc-page-28255-transition", name: "page-28255-transition.php" },
                          { id: "kizuki-kbc-page-28337-transition", name: "page-28337-transition.php" },
                          { id: "kizuki-kbc-page-28363-transition", name: "page-28363-transition.php" },
                          { id: "kizuki-kbc-page-28396-transition", name: "page-28396-transition.php" },
                          { id: "kizuki-kbc-page-28643-transition", name: "page-28643-transition.php" },
                          { id: "kizuki-kbc-page-28743-transition", name: "page-28743-transition.php" },
                          { id: "kizuki-kbc-page-28860-transition", name: "page-28860-transition.php" },
                          { id: "kizuki-kbc-page-28879-transition", name: "page-28879-transition.php" },
                          { id: "kizuki-kbc-page-28887-transition", name: "page-28887-transition.php" },
                          { id: "kizuki-kbc-page-28907-transition", name: "page-28907-transition.php" },
                          { id: "kizuki-kbc-page-28921-transition", name: "page-28921-transition.php" },
                          { id: "kizuki-kbc-page-28937-transition", name: "page-28937-transition.php" },
                          { id: "kizuki-kbc-page-29175-transition", name: "page-29175-transition.php" },
                          { id: "kizuki-kbc-page-29242-transition", name: "page-29242-transition.php" },
                          { id: "kizuki-kbc-page-29244-transition", name: "page-29244-transition.php" },
                          { id: "kizuki-kbc-page-29515-transition", name: "page-29515-transition.php" },
                          { id: "kizuki-kbc-page-29709-transition", name: "page-29709-transition.php" },
                          { id: "kizuki-kbc-page-29773-transition", name: "page-29773-transition.php" },
                          { id: "kizuki-kbc-page-29962-transition", name: "page-29962-transition.php" },
                          { id: "kizuki-kbc-page-29989-transition", name: "page-29989-transition.php" },
                          { id: "kizuki-kbc-page-30003-transition", name: "page-30003-transition.php" },
                          { id: "kizuki-kbc-page-30556-transition", name: "page-30556-transition.php" },
                          { id: "kizuki-kbc-page-30637-transition", name: "page-30637-transition.php" },
                          { id: "kizuki-kbc-page-30697-transition", name: "page-30697-transition.php" },
                          { id: "kizuki-kbc-page-30889-transition", name: "page-30889-transition.php" },
                          { id: "kizuki-kbc-page-31012-transition", name: "page-31012-transition.php" },
                          { id: "kizuki-kbc-page-31986-transition", name: "page-31986-transition.php" },
                          { id: "kizuki-kbc-page-32007-transition", name: "page-32007-transition.php" },
                          { id: "kizuki-kbc-page-32468-transition", name: "page-32468-transition.php" },
                          { id: "kizuki-kbc-page-32493-transition", name: "page-32493-transition.php" },
                          { id: "kizuki-kbc-page-32624-transition", name: "page-32624-transition.php" },
                          { id: "kizuki-kbc-page-33267-transition", name: "page-33267-transition.php" },
                          { id: "kizuki-kbc-page-33287-transition", name: "page-33287-transition.php" },
                          { id: "kizuki-kbc-page-33610-transition", name: "page-33610-transition.php" },
                          { id: "kizuki-kbc-page-33621-transition", name: "page-33621-transition.php" },
                          { id: "kizuki-kbc-page-33799-transition", name: "page-33799-transition.php" },
                          { id: "kizuki-kbc-page-33842-transition", name: "page-33842-transition.php" },
                          { id: "kizuki-kbc-page-33859-transition", name: "page-33859-transition.php" },
                          { id: "kizuki-kbc-page-33897-transition", name: "page-33897-transition.php" },
                          { id: "kizuki-kbc-page-34065-transition", name: "page-34065-transition.php" },
                          { id: "kizuki-kbc-page-34118-transition", name: "page-34118-transition.php" },
                          { id: "kizuki-kbc-page-34129-transition", name: "page-34129-transition.php" },
                          { id: "kizuki-kbc-page-34137-transition", name: "page-34137-transition.php" },
                          { id: "kizuki-kbc-page-34579-transition", name: "page-34579-transition.php" },
                          { id: "kizuki-kbc-page-34692-transition", name: "page-34692-transition.php" },
                          { id: "kizuki-kbc-page-34891-transition", name: "page-34891-transition.php" },
                          { id: "kizuki-kbc-page-34908-transition", name: "page-34908-transition.php" },
                          { id: "kizuki-kbc-page-35051-transition", name: "page-35051-transition.php" },
                          { id: "kizuki-kbc-page-35070-transition", name: "page-35070-transition.php" },
                          { id: "kizuki-kbc-page-35416-transition", name: "page-35416-transition.php" },
                          { id: "kizuki-kbc-page-35430-transition", name: "page-35430-transition.php" },
                          { id: "kizuki-kbc-page-35466-transition", name: "page-35466-transition.php" },
                          { id: "kizuki-kbc-page-35615-transition", name: "page-35615-transition.php" },
                          { id: "kizuki-kbc-page-35642-transition", name: "page-35642-transition.php" },
                          { id: "kizuki-kbc-page-35715-transition", name: "page-35715-transition.php" },
                          { id: "kizuki-kbc-page-35741-transition", name: "page-35741-transition.php" },
                          { id: "kizuki-kbc-page-35798-transition", name: "page-35798-transition.php" },
                          { id: "kizuki-kbc-page-36204-transition", name: "page-36204-transition.php" },
                          { id: "kizuki-kbc-page-36743-transition", name: "page-36743-transition.php" },
                          { id: "kizuki-kbc-page-36795-transition", name: "page-36795-transition.php" },
                          { id: "kizuki-kbc-page-36940-transition", name: "page-36940-transition.php" },
                          { id: "kizuki-kbc-page-37090-transition", name: "page-37090-transition.php" },
                          { id: "kizuki-kbc-page-37165-transition", name: "page-37165-transition.php" },
                          { id: "kizuki-kbc-page-37284-transition", name: "page-37284-transition.php" },
                          { id: "kizuki-kbc-page-37374-transition", name: "page-37374-transition.php" },
                          { id: "kizuki-kbc-page-37464-transition", name: "page-37464-transition.php" },
                          { id: "kizuki-kbc-page-38385-transition", name: "page-38385-transition.php" },
                          { id: "kizuki-kbc-page-47788-transition", name: "page-47788-transition.php" },
                          { id: "kizuki-kbc-page-47914-transition", name: "page-47914-transition.php" },
                          { id: "kizuki-kbc-page-47987-transition", name: "page-47987-transition.php" },
                          { id: "kizuki-kbc-page-47999-transition", name: "page-47999-transition.php" },
                          { id: "kizuki-kbc-page-48005-transition", name: "page-48005-transition.php" },
                          { id: "kizuki-kbc-page-48062-transition", name: "page-48062-transition.php" },
                          { id: "kizuki-kbc-page-48204-transition", name: "page-48204-transition.php" },
                          { id: "kizuki-kbc-page-48334-transition", name: "page-48334-transition.php" },
                          { id: "kizuki-kbc-page-48369-transition", name: "page-48369-transition.php" },
                          { id: "kizuki-kbc-page-48626-transition", name: "page-48626-transition.php" },
                          { id: "kizuki-kbc-page-49082-transition", name: "page-49082-transition.php" },
                          { id: "kizuki-kbc-page-49200-transition", name: "page-49200-transition.php" },
                          { id: "kizuki-kbc-page-49261-transition", name: "page-49261-transition.php" },
                          { id: "kizuki-kbc-page-49333-transition", name: "page-49333-transition.php" },
                          { id: "kizuki-kbc-page-49629-transition", name: "page-49629-transition.php" },
                          { id: "kizuki-kbc-page-49721-transition", name: "page-49721-transition.php" },
                          { id: "kizuki-kbc-page-50564-transition", name: "page-50564-transition.php" },
                          { id: "kizuki-kbc-page-51546-transition", name: "page-51546-transition.php" },
                          { id: "kizuki-kbc-page-51549-transition", name: "page-51549-transition.php" },
                          { id: "kizuki-kbc-page-52506-transition", name: "page-52506-transition.php" },
                          { id: "kizuki-kbc-page-52721-transition", name: "page-52721-transition.php" },
                          { id: "kizuki-kbc-page-52753-transition", name: "page-52753-transition.php" },
                          { id: "kizuki-kbc-page-52932-transition", name: "page-52932-transition.php" },
                          { id: "kizuki-kbc-page-52986-transition", name: "page-52986-transition.php" },
                          { id: "kizuki-kbc-page-53131-transition", name: "page-53131-transition.php" },
                          { id: "kizuki-kbc-page-53161-transition", name: "page-53161-transition.php" },
                          { id: "kizuki-kbc-page-53265-transition", name: "page-53265-transition.php" },
                          { id: "kizuki-kbc-page-53272-transition", name: "page-53272-transition.php" },
                          { id: "kizuki-kbc-page-53593-transition", name: "page-53593-transition.php" },
                          { id: "kizuki-kbc-page-53667-transition", name: "page-53667-transition.php" },
                          { id: "kizuki-kbc-page-53872-transition", name: "page-53872-transition.php" },
                          { id: "kizuki-kbc-page-53888-transition", name: "page-53888-transition.php" },
                          { id: "kizuki-kbc-page-54756-transition", name: "page-54756-transition.php" },
                          { id: "kizuki-kbc-page-54837-transition", name: "page-54837-transition.php" },
                          { id: "kizuki-kbc-page-54911-transition", name: "page-54911-transition.php" },
                          { id: "kizuki-kbc-page-55056-transition", name: "page-55056-transition.php" },
                          { id: "kizuki-kbc-page-55172-transition", name: "page-55172-transition.php" },
                          { id: "kizuki-kbc-page-55219-transition", name: "page-55219-transition.php" },
                          { id: "kizuki-kbc-page-55354-transition", name: "page-55354-transition.php" },
                          { id: "kizuki-kbc-page-55420-transition", name: "page-55420-transition.php" },
                          { id: "kizuki-kbc-page-55441-transition", name: "page-55441-transition.php" },
                          { id: "kizuki-kbc-page-56011-transition-tt", name: "page-56011-transition-tt.php" },
                          { id: "kizuki-kbc-page-56011-transition", name: "page-56011-transition.php" },
                          { id: "kizuki-kbc-page-56610-transition", name: "page-56610-transition.php" },
                          { id: "kizuki-kbc-page-56674-transition", name: "page-56674-transition.php" },
                          { id: "kizuki-kbc-page-57045-transition", name: "page-57045-transition.php" },
                          { id: "kizuki-kbc-page-57048-transition", name: "page-57048-transition.php" },
                          { id: "kizuki-kbc-page-57050-transition", name: "page-57050-transition.php" },
                          { id: "kizuki-kbc-page-57133-transition", name: "page-57133-transition.php" },
                          { id: "kizuki-kbc-page-58762-transition", name: "page-58762-transition.php" },
                          { id: "kizuki-kbc-page-59264-transition", name: "page-59264-transition.php" },
                          { id: "kizuki-kbc-page-59804-transition", name: "page-59804-transition.php" },
                          { id: "kizuki-kbc-page-60849-transition", name: "page-60849-transition.php" },
                        ],
                      },
                      {
                        id: "kizuki-ouen",
                        name: "ouen",
                        children: [
                          { id: "kizuki-ouen-footer-ouen", name: "footer-ouen.php" },
                          { id: "kizuki-ouen-head-ouen", name: "head-ouen.php" },
                          { id: "kizuki-ouen-header-ouen", name: "header-ouen.php" },
                          { id: "kizuki-ouen-page-ouen", name: "page-ouen.php" },
                          { id: "kizuki-ouen-page-ouenTop", name: "page-ouenTop.php" },
                          { id: "kizuki-ouen-sidebar-ouen", name: "sidebar-ouen.php" },
                        ],
                      },
                      { id: "kizuki-page-about", name: "page-about.php" },
                      {
                        id: "kizuki-page-chutai-osaka-top",
                        name: "page-chutai_osaka-top.php",
                      },
                      {
                        id: "kizuki-page-chutai-top",
                        name: "page-chutai-top.php",
                      },
                      {
                        id: "kizuki-page-donationlp-sp",
                        name: "page-donationlp-sp.php",
                      },
                      {
                        id: "kizuki-page-donationlp",
                        name: "page-donationlp.php",
                      },
                      {
                        id: "kizuki-page-form-thanks-yagaku",
                        name: "page-form-thanks-yagaku.php",
                      },
                      {
                        id: "kizuki-page-form-thanks",
                        name: "page-form-thanks.php",
                      },
                      { id: "kizuki-page-form-v2", name: "page-form-v2.php" },
                      { id: "kizuki-page-form", name: "page-form.php" },
                      {
                        id: "kizuki-page-form2-thanks",
                        name: "page-form2-thanks.php",
                      },
                      { id: "kizuki-page-form2", name: "page-form2.php" },
                      {
                        id: "kizuki-page-front-page-test",
                        name: "page-front-page-test.php",
                      },
                      {
                        id: "kizuki-page-futoko-osaka-top",
                        name: "page-futoko_osaka-top.php",
                      },
                      {
                        id: "kizuki-page-futoko-top",
                        name: "page-futoko-top.php",
                      },
                      {
                        id: "kizuki-page-highschool",
                        name: "page-highschool.php",
                      },
                      {
                        id: "kizuki-page-hogosya-osaka-top",
                        name: "page-hogosya_osaka-top.php",
                      },
                      {
                        id: "kizuki-page-hogosya-top",
                        name: "page-hogosya-top.php",
                      },
                      { id: "kizuki-page-kbc-form", name: "page-kbc-form.php" },
                      {
                        id: "kizuki-page-kbc-thanks",
                        name: "page-kbc-thanks.php",
                      },
                      { id: "kizuki-page-parent", name: "page-parent.php" },
                      {
                        id: "kizuki-page-redirect-formbridge-contactform",
                        name: "page-redirect-formbridge-contactform.php",
                      },
                      {
                        id: "kizuki-page-syakaijin-osaka-top",
                        name: "page-syakaijin_osaka-top.php",
                      },
                      {
                        id: "kizuki-page-syakaijin-top",
                        name: "page-syakaijin-top.php",
                      },
                      { id: "kizuki-page-test", name: "page-test.php" },
                      {
                        id: "kizuki-page-top-osaka",
                        name: "page-top_osaka.php",
                      },
                      {
                        id: "kizuki-page-tsushin-high-top",
                        name: "page-tsushin-high-top.php",
                      },
                      {
                        id: "kizuki-page-tsushin-junior-top",
                        name: "page-tsushin-junior-top.php",
                      },
                      { id: "kizuki-page", name: "page.php" },
                      {
                        id: "kizuki-questions",
                        name: "questions",
                        children: [
                          { id: "kizuki-questions-page-questions", name: "page-questions.php" },
                        ],
                      },
                      { id: "kizuki-serach", name: "serach.php" },
                      {
                        id: "kizuki-sidebar-column",
                        name: "sidebar-column.php",
                      },
                      {
                        id: "kizuki-sidebar-monthly",
                        name: "sidebar-monthly.php",
                      },
                      { id: "kizuki-sidebar", name: "sidebar.php" },
                      { id: "kizuki-single-blog", name: "single-blog.php" },
                      { id: "kizuki-single-column", name: "single-column.php" },
                      {
                        id: "kizuki-single-company-2023",
                        name: "single-company-2023.php",
                      },
                      {
                        id: "kizuki-single-company-cookie",
                        name: "single-company-cookie.php",
                      },
                      {
                        id: "kizuki-single-company-withmv",
                        name: "single-company-withmv.php",
                      },
                      {
                        id: "kizuki-single-company",
                        name: "single-company.php",
                      },
                      {
                        id: "kizuki-single-kbc-column-chic",
                        name: "single-kbc-column-chic.php",
                      },
                      {
                        id: "kizuki-single-kbc-staff",
                        name: "single-kbc-staff.php",
                      },
                      {
                        id: "kizuki-single-kbc-teacher",
                        name: "single-kbc-teacher.php",
                      },
                      {
                        id: "kizuki-single-kbc-voice",
                        name: "single-kbc-voice.php",
                      },
                      { id: "kizuki-single-kbc", name: "single-kbc.php" },
                      {
                        id: "kizuki-single-redirect-line-kbc",
                        name: "single-redirect-line-kbc.php",
                      },
                      {
                        id: "kizuki-single-redirect-line",
                        name: "single-redirect-line.php",
                      },
                      {
                        id: "kizuki-single-redirect-select-kbc",
                        name: "single-redirect-select-kbc.php",
                      },
                      {
                        id: "kizuki-single-redirect",
                        name: "single-redirect.php",
                      },
                      {
                        id: "kizuki-single-teachers",
                        name: "single-teachers.php",
                      },
                      { id: "kizuki-single-voice", name: "single-voice.php" },
                      { id: "kizuki-single", name: "single.php" },
                      { id: "kizuki-style", name: "style.css" },
                      { id: "kizuki-tag", name: "tag.php" },
                      {
                        id: "kizuki-targets",
                        name: "targets",
                        children: [
                          { id: "kizuki-targets-page-4sou-chutai", name: "page-4sou-chutai.php" },
                          { id: "kizuki-targets-page-4sou-futoko", name: "page-4sou-futoko.php" },
                          { id: "kizuki-targets-page-4sou-syakaijin", name: "page-4sou-syakaijin.php" },
                          { id: "kizuki-targets-page-4sou-tsushinsei", name: "page-4sou-tsushinsei.php" },
                          { id: "kizuki-targets-page-targets", name: "page-targets.php" },
                        ],
                      },
                      {
                        id: "kizuki-taxonomy-blog-category",
                        name: "taxonomy-blog-category.php",
                      },
                      {
                        id: "kizuki-taxonomy-blog-tag",
                        name: "taxonomy-blog-tag.php",
                      },
                      {
                        id: "kizuki-taxonomy-company-category",
                        name: "taxonomy-company-category.php",
                      },
                      {
                        id: "kizuki-taxonomy-company-tag",
                        name: "taxonomy-company-tag.php",
                      },
                      {
                        id: "kizuki-test",
                        name: "test",
                        children: [
                          { id: "kizuki-test-archive-kbc-test", name: "archive-kbc-test.php" },
                          { id: "kizuki-test-company-front-page-test", name: "company-front-page-test.php" },
                          { id: "kizuki-test-foot-test", name: "foot-test.php" },
                          { id: "kizuki-test-foot-top-test", name: "foot-top-test.php" },
                          { id: "kizuki-test-footer-test", name: "footer-test.php" },
                          { id: "kizuki-test-front-page-test", name: "front-page-test.php" },
                          { id: "kizuki-test-head-test", name: "head-test.php" },
                          { id: "kizuki-test-header-test", name: "header-test.php" },
                          { id: "kizuki-test-page-test", name: "page-test.php" },
                          { id: "kizuki-test-sidebar-test", name: "sidebar-test.php" },
                        ],
                      },
                      {
                        id: "kizuki-video",
                        name: "video",
                        children: [
                          { id: "kizuki-video-digital-strategy-department-mp4", name: "digital-strategy-department.mp4" },
                        ],
                      },
                    ],
                  },
                  {
                    id: "themes-twentytwentyfive",
                    name: "twentytwentyfive",
                    children: [],
                  },
                  {
                    id: "themes-twentytwentyfour",
                    name: "twentytwentyfour",
                    children: [],
                  },
                ],
              },
              { id: "wp-content-upgrade", name: "upgrade", children: [] },
              {
                id: "wp-content-upgrade-temp",
                name: "upgrade-temp-backup",
                children: [],
              },
              { id: "wp-content-uploads", name: "uploads", children: [] },
              // ▲ wp-content_tree.txt (Source 6) の内容を反映 ▲
            ],
          },
          { id: "wp-cron", name: "wp-cron.php" },
          { id: "wp-includes", name: "wp-includes", children: [] }, // フォルダ
          { id: "wp-links-opml", name: "wp-links-opml.php" },
          { id: "wp-load", name: "wp-load.php" },
          { id: "wp-login", name: "wp-login.php" },
          { id: "wp-mail", name: "wp-mail.php" },
          { id: "wp-settings", name: "wp-settings.php" },
          { id: "wp-signup", name: "wp-signup.php" },
          { id: "wp-trackback", name: "wp-trackback.php" },
          { id: "wp-xmlrpc", name: "xmlrpc.php" },
          // ▲ wordpress_tree.txt の内容 ▲
        ],
      },
      {
        id: "wp",
        name: "wp",
        children: [], // 第2階層
      },
      {
        id: "xmailinglist",
        name: "xmailinglist",
        children: [], // 第2階層
      },
    ],
  },
];

/**
 * メインアプリケーションコンポーネント
 * ファイル構造をアコーディオンメニューとして表示
 */
const App = () => {
  return (
    <div className="App">
      <header>
        <h1>アコーディオンメニュー (React)</h1>
      </header>

      <main className="accordion-container">
        <nav aria-label="ファイル構造ナビゲーション">
          <ul className="accordion">
            {FILE_STRUCTURE.map((item) => (
              <AccordionItem key={item.id} item={item} />
            ))}
          </ul>
        </nav>
      </main>
    </div>
  );
};

export default App;